### PR TITLE
Refactoring to avoid using CSS animations that run on CPU

### PR DESCRIPTION
**Pull request by orballo**
fixes https://github.com/frontity/saturn-theme/issues/109

### CODE REVIEW

**Comment by luisherranz** [comment]
@orballo is this ready to merge even tho it's not finished?

**Comment by orballo** [comment]
@luisherranz yes it is

**Comment by luisherranz** [comment]
Ok, then, could you please pull and take a look at my last commits to see if your work is still valid? The merge was kind of complex with the `transitionTime` @DAreRodz did.

**Comment by orballo** [comment]
Oki doki

**Comment by orballo** [comment]
Solved the conflicts. Ready for review.

**Pull request merged**
