### PR TITLE
Add the correct id when type is 'latest'

### LINKED ISSUE #167: Enable lists of custom post type in menu bar
It is only possible to add a custom post type in the menu bar as an external link

### PR DESCRIPTION
**Pull request by DAreRodz**
Fixes #167

### CODE REVIEW

**Comment by luisherranz** [comment]
Is it possible to have `latest` use `id` and in the future change both `category`, `page` and so on... so we keep only a `type` and an `id`?

**Comment by luisherranz** [comment]
Or it's not worth it.

**Comment by DAreRodz** [comment]
@luisherranz I was just following the convention that was used previously, for not changing it for all cases. I mean, I didn't want to use `id` only for` latest`. But, anyway, I agree with using the `id` for this case.

Yes, I think it's worth it.

**Comment by luisherranz** [comment]
This is a mess anyway, so let's leave it as it is. We need to refactor it once we get rid of the old dashboard.

**Pull request merged**
