### PR TITLE
Changes footer logo

### PR DESCRIPTION
**Pull request by orballo**
fixes https://github.com/frontity/saturn-theme/issues/20

### CODE REVIEW

**Comment by luisherranz** [comment]
@orballo you've pushed a commit which doesn't belong here (https://github.com/frontity/saturn-theme/pull/39/commits/0dce5adb7aefeb73470d6563c6959109dbc36347). You can revert and push, then cherry-pick in the correct branch.

**Comment by orballo** [comment]
Ready for review.

**Pull request merged**
