### PR TITLE
Adds galleries with featured and content images

### PR DESCRIPTION
**Pull request by orballo**
fixes https://github.com/frontity/saturn-theme/issues/30

### CODE REVIEW

**Comment by orballo** [comment]
Well, it was done like this because I didn't really think it through 😆 I'll make the changes.

**Comment by luisherranz** [comment]
Ok. I think it'll be cleaner to leave `<Image>` as it is :)

**Comment by orballo** [comment]
Ready for review.

**Comment by orballo** [comment]
Ready to review.

**Pull request merged**
