### PR TITLE
Fixes Media missing mstId prop

### PR DESCRIPTION
**Pull request by orballo**
fixes https://github.com/frontity/saturn-theme/issues/99

### CODE REVIEW

**Comment by orballo** [comment]
@luisherranz I agree with you, but this will take a bit more, because is not the only place where we're sending `mstId`, is happening as well in lists and we are sending the whole `mst` item in posts. And those `mstId`s aren't always just `${type}_${id}`. We should find another way to make it unique in `SmartAd`, I guess.

**Comment by luisherranz** [comment]
We are going to merge this to solve the bug and I'll open an issue to rethink the Fills/Slots APIs.

**Pull request merged**
